str = ''
str += '<div id="footer">'
str += '	<div class="agree_wrap">'
str += '		<ul class="agree">'
str += '			<li><a href="#">이용약관</a><span class="bar"></span></li>'
str += '			<li><a href="#">개인정보취급방침</a></li>'
str += '		</ul>'
str += '	</div>'
str += '	<strong class="mt3">농업회사법인 세종로컬푸드 주식회사</strong>'
str += '	<p class="txt">세종특별자치시 보듬6로 16, (도담동)(도담동)</p>'
str += '	<p class="txt">대표이사 : 최무락 / 사업자등록번호 : 183-88-00128 / Tel : 044-866-4905</p>'
str += '	<p class="txt mt3">Copyright ⓒ 세종로컬푸드주식회사. All rights reserved</p>'
str += '</div>'

document.write(str);