str = ''
str += '<div id="gnb">'
str += ''
str += '	<div class="top">'
str += '		<div class="fl">'
str += '			<a href="index.html"><img src="img/home.png" alt=""></a>'
str += '			<ul>'
str += '				<li><a href="login.html">로그인</a></li>'
str += '				<li><a href="join_01.html">회원가입</a></li>'
str += '			</ul>'
str += '		</div>'
str += '		<div class="fr">'
str += '			<button type="button" class="btn_close">전체메뉴 닫기</button>'
str += '		</div>'
str += '	</div>'
str += ''
str += '	<ul class="depth1">'
str += '		<li>'
str += '			<a href="#">세종형 로컬푸드</a>'
str += '			<ul class="depth2">'
str += '				<a href="sejong_local.html"><li>세종형 로컬푸드</li></a>'
str += '				<a href="sejong_why.html"><li>왜 로컬푸드인가?</li></a>'
str += '			</ul>'
str += '		</li>'
str += '		<li>'
str += '			<a href="#">싱싱장터</a>'
str += '			<ul class="depth2">'
str += '				<a href="market_ceo.html"><li>소개</li></a>'
str += '				<a href="market_farm_list.html"><li>상품소개</li></a>'
str += '			</ul>'
str += '		</li>'
str += '		<li>'
str += '			<a href="#">싱싱문화관</a>'
str += '			<ul class="depth2">'
str += '				<a href="culture_why.html"><li>소개</li></a>'
str += '				<a href="culture_cook.html"><li>요리교실</li></a>'
str += '				<a href="culture_eat.html"><li>싱싱밥상</li></a>'
str += '			</ul>'
str += '		</li>'
str += '		<li>'
str += '			<a href="#">커뮤니티</a>'
str += '			<ul class="depth2">'
str += '				<a href="comm_notice_list.html"><li>공지사항</li></a>'
str += '				<a href="comm_varius_list"><li>이모저모</li></a>'
str += '				<a href="comm_qa_myinfo.html"><li>문의</li></a>'
str += '			</ul>'
str += '		</li>'
str += '		<li>'
str += '			<a href="#">내정보</a>'
str += '			<ul class="depth2">'
str += '				<a href="myinfo_01.html"><li>소비자회원</li></a>'
str += '				<a href="myinfo_06.html"><li>생산자(전용)</li></a>'
str += '			</ul>'
str += '		</li>'
str += '	<ul>'
str += '	<div class="btm">COPYRIGHT 세종로컬푸드주식회사 ALL RIGHTS RESERVED.</div>'
str += '</div>'
str += ''
str += '<div id="dim" class="backface"></div>'
str += ''
str += '<div id="h_search" class="top_search_wrap">'
str += '	<form action="#" method="post" name="">'
str += '		<div class="s_wrap">'
str += '			<div class="fl"><input type="text" name="keyword" class="w100" value=""></div>'
str += '			<div class="fr"><a href="javascript:" class="btn w100">검색</a></div>'
str += '		</div>'
str += '	</form>'
str += '</div>'

document.write(str);